In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_Embarked = pickle.load(open('models/ohe_Embarked.pkl','rb'))
dt_clf = pickle.load(open('models/dt_clf.pkl','rb'))

In [3]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [5]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
test_input_sex

array([[0., 1.]])

In [17]:
test_input_Embarked = ohe_Embarked.transform(test_input[:,-1].reshape(1,1))

C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [18]:
test_input_Embarked

array([[0., 0., 1., 0.]])

In [19]:
test_input_age = test_input[:,2].reshape(1,1)

In [20]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_Embarked),axis=1)

In [21]:
test_input_transformed.shape

(1, 11)

In [22]:
dt_clf.predict(test_input_transformed)

array([0], dtype=int64)